name: Run Your Python Script

on:
  schedule:
    - cron: '0 10 * * *'  # 在UTC时间中午12点运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 选择所需的 Python 版本

    - name: Install dependencies
      run: pip install -r requirements.txt  # 根据你的需求修改 requirements.txt 文件路径

    - name: Run Python script
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        ACCOUNTS_AND_PASSWORDS: ${{ secrets.ACCOUNTS_AND_PASSWORDS }}
      run: python py.py # 根据你的脚本文件名修改这里

    - name: Send Telegram Notification
      if: always()  # 无论成功还是失败都发送通知
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_API_TOKEN }}
        text: "Python script has been executed."
