name: Run Your Python Script

on:
  schedule:
    - cron: '0 11 * * *'  # 在UTC时间上午11点运行
  push :
         branches: 
          - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 选择所需的 Python 版本

    - name: Install dependencies
      run: pip install -r requirements.txt  # 根据你的需求修改 requirements.txt 文件路径

    - name: Run Python script
      id: run_python
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        ACCOUNTS_AND_PASSWORDS: ${{ secrets.ACCOUNTS_AND_PASSWORDS }}
      run: |
        python py.py  # 根据你的脚本文件名修改这里
        echo "::set-output name=ran_successfully::true"  # 标记成功执行

    - name: Notify on Telegram if successful
      if: steps.run_python.outputs.ran_successfully == 'true'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_API_TOKEN }}
        message: "Python script ran successfully!"
